# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTestApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
  pod 'AlamofireNetworkActivityIndicator', '~> 3.1'
  pod 'Moya/RxSwift', '~> 15.0'
  pod "PromiseKit/CorePromise", "~> 6.8"

end
